### ISSUE TITLE
X11 recognisces the 3 fingers as a middle-click and pastes what you have copied

### ISSUE THREAD

**Issue by mulus1466** [JoseExposito/gnome-shell-extension-x11gestures#12]
### Is your feature request related to a problem? Please describe

As this extension is used with X11, it sometimes recognizes the 3 finger gestures as a middle-click, so it pastes whatever you have copied.

### Describe the solution you'd like

It would be awesome if the extension itself could disable the 3 finger pasting, or give the option to do so.

### Describe alternatives you've considered

I disabled the middle-click pasting by using some [xinput magic I found in Stack Exchange](https://superuser.com/questions/1300966/touch-pad-usage-will-randomly-copy-paste-text-from-the-screen), so it's also an option to leave a warning and some instructions, or something.

**Comment by JoseExposito** [comment]
Hi,

Three fingers tap to copy and paste is the default behaviour in most (all?) Linux desktop environments.

Aparenly, there is an option to disable it in GNOME Tweaks, in case you want to disable it:
https://askubuntu.com/a/1214767

Implementing it in this extension is a bit out of the scope of the extensions, but hopefully you can configure it with GNOME Tweaks.
