### ISSUE TITLE
Compatibility for gnome 40.3

### ISSUE THREAD

**Issue by Jabir-Srj** [JoseExposito/gnome-shell-extension-x11gestures#17]
Is it possible to create compatibility for gnome 40.3?
Apparently I can't install it. I don't know if this helps.
![Screenshot from 2021-07-15 16-11-49](https://user-images.githubusercontent.com/76161308/125794427-e87426ec-97b9-43f9-a7b7-9c19361c6dd7.png)
[admin@lenovo-80x8 ~]$ gnome-shell --version
GNOME Shell 40.3

**Comment by JoseExposito** [comment]
Just released a new version, you should be able to install it now.
