### ISSUE TITLE
Horizontal workspace switching on GNOME 3.38

### ISSUE THREAD

**Issue by JJGadgets** [JoseExposito/gnome-shell-extension-x11gestures#2]
### Is your feature request related to a problem? Please describe

I have Workspace to Dock, which enables horizontal workspace switching instead of vertical on 3.38, which I prefer. Currently, X11 Gestures seems to not respect the horizontal switching. Even though in Touchegg I have 4 finger up and down disabled, only 4F left & right for switching workspaces, X11 Gestures will still use 4 finger up & down instead of respecting Touchegg.

### Describe the solution you'd like

Either have settings in GNOME Extensions to specify if gestures for workspace switching should be vertical or horizontal
OR
Respect Touchegg's "Switch desktop" option and follow the appropriate gesture specified.

**Comment by JoseExposito** [comment]
The number of extension that can "break" the default behavior are virtually infinite. Unfortunately, I can not add support for all of them. Even if I try to do something with this extension, it'll fail with, let's say that extension that transforms your workspaces in a grid. Even worst, it'll fail in different ways depending on the GNOME version.

Closing the issue as it is out of the scope of this extension.
