### ISSUE TITLE
Extension does not detect Touchegg installed on NixOS

### ISSUE THREAD

**Issue by maydayv7** [JoseExposito/gnome-shell-extension-x11gestures#21]
### Describe the bug

When the X11 Gestures extension is installed from either the Extensions website or the [nixpkg](https://search.nixos.org/packages?channel=21.05&show=gnomeExtensions.x11-gestures&from=0&size=50&sort=relevance&type=packages&query=x11+gestures) and session is restarted, the" Touchegg is not installed" message appears. Even though the notification is displayed, the gestures work properly, but the default Touchegg gestures are not inhibited. For example, a 3 finger swipe-up results in both switching to the activities overview as well as maximizing the currently focused application. This may be because the path for detecting Touchegg is hardcoded, but in NixOS installed packages installed have different paths (in /nix/store) as compared to conventional behaviour of other distros.

### Expected behaviour

The extension must detect the Touchegg package that is installed on the system, inhibit the default gestures, and work properly

### Logs

No logs found with the command `journalctl -f -o cat /nix/store/knybxcvc53l8phjfvlirxzwqv4p6xg2z-gnome-shell-40.1/bin/gnome-shell`

### Your environment

 * Extension version: 8
 * Touchégg version: 2.0.11
 (Touchegg is installed manually via using [this](https://github.com/maydayv7/pc-stuff/blob/master/NIX/overlays/touchegg.nix) Nix Overlay, as the nixpkg for it is outdated)
 * Operating System: NixOS 21.05
 ([This](https://github.com/maydayv7/pc-stuff/tree/master/NIX) is the config for my installed system, it is completely reproducible)
 * GNOME Shell Version: 40.1

**Comment by JoseExposito** [comment]
I believe this is a known issue by the NixOS devs, see https://github.com/JoseExposito/gnome-shell-extension-x11gestures/issues/19.

This needs to be reported to the packagers of the extension, hopefully they can help you.

**Comment by maydayv7** [comment]
Actually, no, that was because the tochegg package provided in the repos was outdated, but I am running the latest version v2.0.11, that I manually installed using an overlay (link to it is given in the first comment)

**Comment by JoseExposito** [comment]
Yes, but this extension checks if Touchégg is installed by looking at the config file in `/usr`. It also needs to know where is your personal config (in home) to reserve the gestures to GNOME and don't run 2 actions.

Those two paths need to be patched by the extension packager. I believe that the easiest way to fix this issue is to open a bug report in the NixOS bug tracker. If you share the link I can try to clarify what's needed.

**Comment by maydayv7** [comment]
Okay, there is a relevant [PR](https://github.com/NixOS/nixpkgs/pull/137131) for patching all GNOME Extensions installed via nixpkgs.

**Comment by maydayv7** [comment]
I have opened an [issue](https://github.com/NixOS/nixpkgs/issues/137621)

**Comment by ThatOtherAndrew** [comment]
@maydayv7 Hello, sorry for necroposting but your nixos-config repo is no longer accessible. Could you please give me a quick Overlays-for-Dummies-esque snippet to chuck in to fix this issue for myself? I'm assuming that if I update Touchégg then the shell extension will work as well.

**Comment by ThatOtherAndrew** [comment]
Right, I see. I've still been having issues with Touchégg being detected on NixOS - I'll do a bit more digging and see if I can figure this out.
