### ISSUE TITLE
Bug with the extension and conky

### ISSUE THREAD

**Issue by Stalkerfish** [JoseExposito/gnome-shell-extension-x11gestures#23]
When I swipe three fingers to slide through the workspaces while inside any application, the conky goes to the foreground.

![image](https://user-images.githubusercontent.com/69297165/137669240-e5adab60-16c8-4da1-b580-52f670a2eb5c.png)

This is how it looks while I am holding three fingers.

It does not really bothers or anything, but maybe there's a quick fix and you just didn't notice.

Thanks for this, its a really good extension.

**Comment by JoseExposito** [comment]
Hi,

I can see the same bug on Wayland, where this extension is not used to handle gestures. Try to report the bug to conky devs, the bug is either on their side or in GNOME Shell.
