### ISSUE TITLE
Two finger horizontal swipe for web navigation

### ISSUE THREAD

**Issue by suleymankalkan** [JoseExposito/gnome-shell-extension-x11gestures#26]
### Is your feature request related to a problem? Please describe
If you are using chrome on windows, for example, you can do 2 fingers right/left swipe to go back/forward page.
I am really frustrated because I can't do it on Linux. It is such a great way to navigate while browsing and using a touchpad.
### Describe the solution you'd like

When I swipe to left or right with my 2 fingers (horizontally), I want it to trigger the go back/forward command in the browser.

### Describe alternatives you've considered

I can't think of any other alternative.

### Additional context

.

**Comment by JoseExposito** [comment]
Hi and thanks for your big report.

Unfortunately, it is not possible to perform such an action from a GNOME Shell extension. The browser (Chrome in this case) should implement this feature.

For example, GNOME Web implements 2 finger navigation quite well.

You can try to request this feature to the Chromium developers, but I'm sure there is already a feature request in their bug tracker.
