### ISSUE TITLE
First swipe up enters the Appgrid, if GNOME Shell doesn't start in the overview

### ISSUE THREAD

**Issue by Leleat** [JoseExposito/gnome-shell-extension-x11gestures#27]
### Describe the bug

The first swipe up enters the Appgrid, if GNOME Shell doesn't start in the overview.

STR:
- reload GNOME Shell with `Alt`+`F2` while you are on the desktop. Then swipe up.
- alternatively, use an extension to prevent booting into the overview such as https://extensions.gnome.org/extension/4099/no-overview/

### Expected behaviour

Open the overview.

### Actual behaviour

Opened the AppGrid.

### Logs

Nothing in the logs and (I think) I use the default config.

### Your environment

 * Extension version: 12
 * Touchégg version: v2.0.11
 * Operating System:  Fedora 34
 * GNOME Shell Version: 40.4

**Comment by Leleat** [comment]
> I'm using Just Perfection to avoid showing the overview on startup and I'm not able to reproduce the issue.
> 
> Also, restarting GNOME Shell while on the desktop doesn't trigger it.
> 
> I think this is an issue with how the no overview extension works. Could you try with Just Perfection just to double check, please?

It appears `just perfection` prevents the bug from happening. You should be able to reproduce this by disabling the just-perfection extension and reloading GNOME-Shell... although, I only reload GNOME Shell to live-text my own extension, so I guess this is more of an edge case than a bug since most people wouldn't be able to start GNOME Shell and be immediately in the desktop with some sort of extension...

**Comment by JoseExposito** [comment]
Yes, it is a bit of an edge case to fix it, to be honest.

It requires installing another extension or reloading GNOME Shell, which is not that common, plus the side effect is one missing swipe, not a crash or similar.

Closing it as won't fix for the reasons explained.
