### ISSUE TITLE
3 fingers Swipe UP not working after Session Lock and Login

### ISSUE THREAD

**Issue by ibracadapra** [JoseExposito/gnome-shell-extension-x11gestures#30]
### Describe the bug
After Lock GNOME session and login  the 3 fingers swipe up to show the activities overview is not working (But the animation is working)
All other functionalities still works properly 
When restarting GNOME shell (alt+F2 -> r ) everything then is working.

### Expected behaviour
The 3 fingers swipe up should show the overview

### Logs

If required, include logs of the bug:

```
$ journalctl -f -o cat /usr/bin/gnome-shell

Object Clutter.Actor (0x55e05a58a390), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
JS ERROR: Exception in callback for signal: hidden: TypeError: this._container.layout_manager is undefined
_doneLeavingOverview@resource:///org/gnome/shell/ui/workspace.js:1371:9
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
_hideDone@resource:///org/gnome/shell/ui/overview.js:629:18
onComplete@resource:///org/gnome/shell/ui/overview.js:401:37
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:85:13
_easeActorProperty@resource:///org/gnome/shell/ui/environment.js:224:17
init/St.Adjustment.prototype.ease@resource:///org/gnome/shell/ui/environment.js:302:27
gestureEnd@resource:///org/gnome/shell/ui/overviewControls.js:757:31
_gestureEnd@resource:///org/gnome/shell/ui/overview.js:406:33
_endGesture@resource:///org/gnome/shell/ui/swipeTracker.js:744:14
onToucheggGestureEnd@/home/ibraheem/.local/share/gnome-shell/extensions/x11gestures@joseexposito.github.io/src/v40/SwipeTracker40.js:105:12
emitGestureEvent@/home/ibraheem/.local/share/gnome-shell/extensions/x11gestures@joseexposito.github.io/src/touchegg/ToucheggClient.js:227:12
onNewMessage@/home/ibraheem/.local/share/gnome-shell/extensions/x11gestures@joseexposito.github.io/src/touchegg/ToucheggClient.js:188:10
Object Clutter.Actor (0x55e05e67cc60), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
JS ERROR: Exception in callback for signal: hidden: TypeError: this._container.layout_manager is undefined
_doneLeavingOverview@resource:///org/gnome/shell/ui/workspace.js:1371:9
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
_hideDone@resource:///org/gnome/shell/ui/overview.js:629:18
onComplete@resource:///org/gnome/shell/ui/overview.js:401:37
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:85:13
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:246:60

```

### Your environment

 * Extension version: 12
 * Touchégg version: 2.0.11
 * Operating System: Manjaro
 * GNOME Shell Version: 40.4.0

**Comment by JoseExposito** [comment]
Hi @ibracadapra 

Thanks for reporting the issue and for the logs.

Are you using any other extension? If so, could you temporary disable them and double check if the error still happens, please?

**Comment by ibracadapra** [comment]
@JoseExposito 
I tried to disable all the extensions other than x11 gestures 
and still the same

**Comment by JoseExposito** [comment]
Hi @ibracadapra,

Sorry for the delay fixing this bug.

I didn't manage to reproduce it, after lock/log in I'm still able to open the overview view, but I see some errors in my journal. Hopefully fixing those your error should be fixed as well.

You can easily test if the problem is fixed by extracting the attached zip file in `~/.local/share/gnome-shell/extensions`. If so, I'll create a new release so the fix is available for everyone.

[x11gestures@joseexposito.github.io.zip](https://github.com/JoseExposito/gnome-shell-extension-x11gestures/files/7631534/x11gestures%40joseexposito.github.io.zip)

**Comment by ibracadapra** [comment]
Thanks @JoseExposito , the problem is fixed with the new release 💜

**Comment by vvitez** [comment]
@JoseExposito Oh my god, this fixed the bug I reported a long while ago but didn't know it happens only after locking :DD. Just awesome man. Thanks for doing god's work here.
