### ISSUE TITLE
Gestures not working on Manjaro Gnome

### ISSUE THREAD

**Issue by shawn1thompson** [JoseExposito/gnome-shell-extension-x11gestures#31]
### Describe the bug

The only gesture that seems to work is when in Workspace switching mode, the two finger gesture to switch workspaces. Touchegg, Touche, and the Gnome extension are all installed. In Touche, most gestures say used by Gnome.

### Expected behaviour

All Gnome gestures should work or should be able to configure gestures in Touche.

### Actual behaviour
see above

### Logs

If required, include logs of the bug:

```
$ journalctl -f -o cat /usr/bin/gnome-shell
[x11gestures@joseexposito.github.io] Reconnecting to Touchégg daemon in 5 seconds
[x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
[x11gestures@joseexposito.github.io] Error connecting to Touchégg daemon: Could not connect: Connection refused

```

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.
I haven't changed; hence, it should be the default config.

### Your environment

 * Extension version: 11
 * Touchégg version: 2.0.11-1
 * Operating System: Ubuntu, Fedora, Arch Linux... Manjaro Linux \r  (\n) (\l)
 * GNOME Shell Version: GNOME Shell 40.5
 * Are you using other GNOME Shell extensions?
    * List the other extensions 
    * appindicatorsupport@rgcjonas.gmail.com
apps-menu@gnome-shell-extensions.gcampax.github.com
arcmenu@arcmenu.com
auto-move-windows@gnome-shell-extensions.gcampax.github.com
dash-to-dock@micxgx.gmail.com
dash-to-panel@jderose9.github.com
ding@rastersoft.com
drive-menu@gnome-shell-extensions.gcampax.github.com
gamemode@christian.kellner.me
gnome-ui-tune@itstime.tech
gsconnect@andyholmes.github.io
launch-new-instance@gnome-shell-extensions.gcampax.github.com
material-shell@papyelgringo
native-window-placement@gnome-shell-extensions.gcampax.github.com
nightthemeswitcher@romainvigier.fr
pamac-updates@manjaro.org
places-menu@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
unite@hardpixel.eu
user-theme@gnome-shell-extensions.gcampax.github.com
vertical-overview@RensAlthuis.github.com
window-list@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com
x11gestures@joseexposito.github.io
    * Can you reproduce the issue after disabling the other extensions? I haven't tried.

**Comment by JoseExposito** [comment]
Hi, it looks like the Touchégg daemon is not running. Have you enabled it?
https://github.com/JoseExposito/touchegg#arch-linux-manjaro-and-derivatives

**Comment by shawn1thompson** [comment]
Not explicitly. I would assume it should already be with the packages being preinstalled and configured in Manjaro. Maybe this is something they need to be aware of? How do I enable it?

**Comment by shawn1thompson** [comment]
Yeah, I didn't install it; so, I assume it was. I'll try to raise it on their side. That worked though. Thanks.

**Comment by JoseExposito** [comment]
Great!
