### ISSUE TITLE
Notification to install touchegg when not installed

### ISSUE THREAD

**Issue by Ghibranalj** [JoseExposito/gnome-shell-extension-x11gestures#34]
### Problem : no idiot proofing
Im an idiot and have ADD. I definitely only skimmed the description of this extension and skipped the part where this extension need touchegg to work. it would be nice if the extension would warn me that i need to install touchegg to work. 
*i understand however if you don't agree*. but in my view this is about accessibility and everything should be accessible to everyone.

### Describe the solution you'd like
A constant annoying warning that touchegg is needed :D

cheers

**Comment by JoseExposito** [comment]
You are not an idiot, the way the extension is distributed makes impossible to ship dependencies.
Ideally everything should be installed in a single click, but with the extension being distributed using GNOME Shell Extensions and Touchégg from a PPA or COPR or AUR or your distro favorite package, having a sane installation process is not possible.

Having said that, the extension should display a [notification](https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/067c00a4bb38c243dd26391d9d58c936bde6e787/extension.js#L43) if Touchégg is not installed.
Clicking in the notification should open Touchégg's project page with all the install options available.

If this is not the case, then there is a bug I need to fix. Was it not working in your case?

**Comment by Ghibranalj** [comment]
No there was no notification

**Comment by JoseExposito** [comment]
What distro are you using? I'll see if I can fix it

**Comment by Ghibranalj** [comment]
Im on arch linux and ive tried it on 3 of my arch install no notification.
output of `uname -r` is 5.16.10-arch1-1

**Comment by JoseExposito** [comment]
Tested on an Arch VM (thanks good archinstall is included by default) and I can see the notification:

![image](https://user-images.githubusercontent.com/1335948/155482762-961a380f-3ea7-491b-bd5d-ef127a798bbe.png)

If you installed the extension from AUR, it pulls the dependencies, including Touchégg, so the extension won't complain, even if the service is not enabled, most likely why it wasn't working.

Closing the issue. I wish I could simplify the installation procces...
