### ISSUE TITLE
Add GNOME 42 to compatible versions

### ISSUE THREAD

**Issue by adryd325** [JoseExposito/gnome-shell-extension-x11gestures#35]
I've tested with GNOME 42 and it seems to be compatible with no issue

**Comment by JoseExposito** [comment]
Thanks for testing it! I added support in the metadata file for GNOME 42. I'll wait a bit until GNOME 42 is closer to be released and publish a new version.

**Comment by qwertychouskie** [comment]
Gnome 42 just landed in Ubuntu's repos for 22.04, would be nice to have this extension updated.

**Comment by JoseExposito** [comment]
Released https://github.com/JoseExposito/gnome-shell-extension-x11gestures/releases/tag/14

It'll be available in https://extensions.gnome.org/extension/4033/x11-gestures/ after review
