### ISSUE TITLE
2 finger swipe to go back in Firefox

### ISSUE THREAD

**Issue by vescovaccio** [JoseExposito/gnome-shell-extension-x11gestures#37]
I can set a four finger swipe left to go a page back in Firefox (alt+left), and a four finger swipe right to go a page forward (alt+right). Everything works perfectly.

Then if I edit the touchegg.conf and simply change the four fingers to two fingers, it stops working, even though a two finger swipe isn't assigned anywhere else. The swipe simply has no response.

So the expected behaviour is I can use 2 fingers instead of four, but it doesn't seeem to work.

I also noticed that the Touché desktop app simply doesn't have 2 fingers as an option, only 3 and 4.

Is there some reason for this?

Is there some reason why 2 doesn't work?

Is it blocked for some valid reason? For example, could be confused with scroll left/right or pinch?

It's just that I know it worked before with libinput-gestures - it could tell the difference between a vertical 2 finger swipe (fingers moving parallel) and a horizontal 2 finger swipe (one finger following in the path of the other), or any pinch 

Many thanks!

**Comment by JoseExposito** [comment]
I'm afraid this is not possible, 2 finger swipe is reserved for the OS, as explained in the FAQs, you can request this to the Firefox Devs:
https://github.com/JoseExposito/touchegg#can-i-use-2-finger-swipes-for-web-browser-navigation

**Comment by vescovaccio** [comment]
Many thanks José! I was able to use it (2 finger swiping) before, by using xdotool and libinput-gestures, possibly a little hacky as a solution, but I much prefer your general implementation. Your gestures and animations are extremely well polished. I will look into making a feature request to Mozilla. It would make it a more consistent behaviour regards expectations from users coming from other OSes, and two finger swiping is simply more comfortable and accessible than four finger swiping. Once again, many thanks for your great work.

**Comment by vescovaccio** [comment]
And sorry for not reading the FAQs carefully enough!!
