### ISSUE TITLE
How to open the application?

### ISSUE THREAD

**Issue by dyaskur** [JoseExposito/gnome-shell-extension-x11gestures#39]
How to open the application? On the gnome web page there is no open/launch button, only setting button and there is only 1 setting "Number of finger" I need an application window like on the video/gif.

 * Extension version: 14
 * Touchégg version: 2.0.14
 * Operating System: Ubuntu 22.04
 * GNOME Shell Version: 42

**Comment by JoseExposito** [comment]
Hi!

You don't need to open the app in order to start using gestures, they should work once the extension is installed.

You might want to install Touché from FlatHub to configure your gestures:
https://github.com/JoseExposito/touche
