### ISSUE TITLE
Add gesture handler from another extension

### ISSUE THREAD

**Issue by Thesola10** [JoseExposito/gnome-shell-extension-x11gestures#40]
### Is your feature request related to a problem? Please describe

I am a user and contributor of [PaperWM](https://github.com/PaperWM-community/PaperWM), and I love its gesture handling on Wayland. I would like to know if it is possible to have PaperWM interface with this extension in order to retrieve the three-finger gesture on X11, and if so, how? I'm willing to implement the PaperWM side of things myself.

### Describe the solution you'd like

An API not too dissimilar from Clutter's gesture events, which could be used from a third-party extension

### Describe alternatives you've considered

Not much yet.

### Additional context

I want to run GNOME on X11 to be able to use SteamVR (because the Wayland version [cannot](https://gitlab.gnome.org/GNOME/mutter/-/issues/1743)), and I want the gestures to work on that as well. Otherwise, Wayland works just fine on my system

**Comment by JoseExposito** [comment]
Hi,

Yes, it is possible. This extension relies on [Touchégg](https://github.com/JoseExposito/touchegg)'s D-Bus API to receive gestures. 

You could have a look to the code of this extension and modify it for your needs.

You can find a similar example in [Gala](https://github.com/elementary/gala). A Mutter based WM that also uses Touchégg's D-Bus API to implement gestures on X11.
