### ISSUE TITLE
3 finger swipe types "S"

### ISSUE THREAD

**Issue by sunjerry019** [JoseExposito/gnome-shell-extension-x11gestures#41]
### Describe the bug

When doing the three-finger swipe up to access the "Overviews" while the cursor is in a text field (e.g. in Sublime Text), an "S" will be typed, or it will be typed in the search of the overview. This happens occasionally, but often.

### Expected behaviour

Gnome goes into overview only

### Actual behaviour

Gnome goes into overview and types "S" in the text field occasionally.

### Your environment

 * Extension version: 14
 * Touchégg version: v2.0.14
 * Operating System: Arch Linux
 * GNOME Shell Version: 42.4
 * Are you using other GNOME Shell extensions?
    * Yes: Blur my shell 43, Disconnect Wifi 31, Display DDC Brightness & Volume 5, gTile 50, LAN IP Address 10, Lock Keys 47, No overview at start-up 11, Removable Drive Menu 51, Remove App Menu 9, Simple net speed 28, Tray-icons: Reloaded 25, Vitals 55 
    * Can you reproduce the issue after disabling the other extensions? Yes

**Comment by JoseExposito** [comment]
Hi,

I can imagine you are using the default configuration. You can use Touche to edit it:
https://github.com/JoseExposito/touche

Or manually by editing `~/.config/touchegg/touchegg.conf`.

Since you are using this GNOME Shell extension, you don't need the Super+S shortcut present there. Make sure to remove it and the problem should disappear.

**Comment by sunjerry019** [comment]
Hi there, what should I be changing in the touchegg config?

I have disabled the Super+S shortcut, but the problem is still present. 

If I were to 3-finger swipe up quickly, an "S" also gets typed in the search bar.

**Comment by JoseExposito** [comment]
Could you attach your `~/.config/touchegg/touchegg.conf` file, please? Let's have a look and see what's going on.

**Comment by sunjerry019** [comment]
```
<touchégg>
  <settings>
    <property name="animation_delay">150</property>
    <property name="action_execute_threshold">20</property>
    <property name="color">auto</property>
    <property name="borderColor">auto</property>
  </settings>
  <application name="All">
    <gesture type="PINCH" fingers="3" direction="IN">
      <action type="CLOSE_WINDOW">
        <animate>true</animate>
        <color>F84A53</color>
        <borderColor>F84A53</borderColor>
      </action>
    </gesture>
    <gesture type="PINCH" fingers="4" direction="OUT">
      <action type="SHOW_DESKTOP">
        <animate>true</animate>
      </action>
    </gesture>
    <gesture type="PINCH" fingers="4" direction="IN">
      <action type="SEND_KEYS">
        <repeat>false</repeat>
        <modifiers>Super_L</modifiers>
        <keys>A</keys>
        <on>begin</on>
      </action>
    </gesture>
    <gesture type="TAP" fingers="2" direction="UNKNOWN">
      <action type="MOUSE_CLICK">
        <button>3</button>
        <on>begin</on>
      </action>
    </gesture>
    <gesture type="TAP" fingers="3" direction="UNKNOWN">
      <action type="MOUSE_CLICK">
        <button>2</button>
        <on>begin</on>
      </action>
    </gesture>
    <gesture type="SWIPE" fingers="3" direction="UP">
      <action type="GNOME_SHELL"></action>
    </gesture>
    <gesture type="SWIPE" fingers="3" direction="DOWN">
      <action type="GNOME_SHELL"></action>
    </gesture>
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="GNOME_SHELL"></action>
    </gesture>
    <gesture type="SWIPE" fingers="3" direction="RIGHT">
      <action type="GNOME_SHELL"></action>
    </gesture>
    <gesture type="SWIPE" fingers="4" direction="UP">
      <action type="MAXIMIZE_RESTORE_WINDOW"></action>
    </gesture>
    <gesture type="SWIPE" fingers="4" direction="LEFT">
      <action type="TILE_WINDOW">
        <direction>left</direction>
      </action>
    </gesture>
    <gesture type="SWIPE" fingers="4" direction="RIGHT">
      <action type="TILE_WINDOW">
        <direction>right</direction>
      </action>
    </gesture>
  
<gesture type="SWIPE" fingers="3" direction="LEFT"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="3" direction="RIGHT"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="3" direction="UP"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="3" direction="DOWN"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="3" direction="LEFT"><action type="GNOME_SHELL"></action></gesture>
<gesture type="SWIPE" fingers="3" direction="RIGHT"><action type="GNOME_SHELL"></action></gesture>
</application>
  <application name="chromium-browser">
    <gesture type="PINCH" fingers="2" direction="IN">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>KP_Subtract</keys>
        <decreaseKeys>KP_Add</decreaseKeys>
      </action>
    </gesture>
    <gesture type="PINCH" fingers="2" direction="OUT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>KP_Add</keys>
        <decreaseKeys>KP_Subtract</decreaseKeys>
      </action>
    </gesture>
  </application>
  <application name="firefox">
    <gesture type="PINCH" fingers="2" direction="IN">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>KP_Subtract</keys>
        <decreaseKeys>KP_Add</decreaseKeys>
      </action>
    </gesture>
    <gesture type="PINCH" fingers="2" direction="OUT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>KP_Add</keys>
        <decreaseKeys>KP_Subtract</decreaseKeys>
      </action>
    </gesture>
  </application>
  <application name="google-chrome">
    <gesture type="PINCH" fingers="2" direction="IN">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>KP_Subtract</keys>
        <decreaseKeys>KP_Add</decreaseKeys>
      </action>
    </gesture>
    <gesture type="PINCH" fingers="2" direction="OUT">
      <action type="SEND_KEYS">
        <repeat>true</repeat>
        <modifiers>Control_L</modifiers>
        <keys>KP_Add</keys>
        <decreaseKeys>KP_Subtract</decreaseKeys>
      </action>
    </gesture>
  </application>
</touchégg>
```

**Comment by JoseExposito** [comment]
The configuration file seems correct... I don't think that Touchégg is the one writing that "S" to the search bar.

Do you mind to run:

```
$ killall touchegg # Important, do NOT use sudo
$ touchegg --debug
```

And attach the output of the console after performing a 3 finger swipe up gesture, please?

Restarting runs Touchégg as usual and put thinks back to normal.

**Comment by sunjerry019** [comment]
I can't `killall touchegg` as a normal user: `touchegg(568): Operation not permitted`

**Comment by JoseExposito** [comment]
Yeah, don't worry, that's normal. There are 2 Touchégg processes. The service (run as root, the one that shows the error, we do NOT want to kill that one) the the client. You already killed the client.

You can run `touchegg --debug` now.

**Comment by sunjerry019** [comment]
Alright, I got:

```
Touchégg v2.0.14.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/<user>/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Gnome-terminal
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
SGesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: DOWN
	Gesture performed on app: 
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
```

**Comment by JoseExposito** [comment]
Mmmm yes, I see the S being sent to the terminal, however, I also see: "Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)".

That message means that Touchégg is not executing any action, so it is not possible that it is writing that "S".

Just to discard other possible issues:

- Does the same happens with the GNOME Shell extension disabled?
- Does the same happens without Touchégg running? (Control + C in the terminal you just used to copy&paste the logs)

**Comment by sunjerry019** [comment]
* With GNOME Shell extensions disabled, the gesture does not work, but the "S" is still being typed (interesting)
* Without Touchégg running, and GNOME Shell extensions enabled, the gesture still works, and the "S" is still being typed

Now I am confused as to where the problem could lie...

**Comment by sunjerry019** [comment]
If I were to kill the daemon running as `root`, the gesture stop working, but the "S" is still being typed, albeit only on three-finger swipe up and not swipe down.

**Comment by sunjerry019** [comment]
Hi there, I have managed to fix this issue by uninstalling `libinput-gestures`. Turns out that was not needed for gestures to work. 

Thanks for the help!

**Comment by JoseExposito** [comment]
Cool, I'm glad you found the issue :)
