### ISSUE TITLE
Gnome 43 support

### ISSUE THREAD

**Issue by qwertychouskie** [JoseExposito/gnome-shell-extension-x11gestures#42]
Gnome 43 is out and this extension is not yet supported, any ETA on an update?

**Comment by JoseExposito** [comment]
It depends, if you could test the extension in GNOME 43 it'll speed up things quite a lot.

It is easy, you'd need to download the source code and follow the instructions in the "debugging" section:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/master/HACKING.md

Then add 43 to: https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/master/metadata.json

And reload GNOME Shell and check if it works.

**Comment by Feinzer** [comment]
> It depends, if you could test the extension in GNOME 43 it'll speed up things quite a lot.
> 
> It is easy, you'd need to download the source code and follow the instructions in the "debugging" section: https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/master/HACKING.md
> 
> Then add 43 to: https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/master/metadata.json
> 
> And reload GNOME Shell and check if it works.

Hi. I just did this. 

Running the extension GNOME 43 on openSUSE Tumbleweed with my Thinkpad x250 and everything seems to be working.

I'm able to switch workspaces, go into the workspace view and so on. Logs on journalctl seems to be some normal GNOME warnings

**Comment by JoseExposito** [comment]
Thanks a lot for testing it @Feinzer , I just released a new version supporting GNOME 43:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/releases/tag/15

And it is also available on GNOME Extensions:
https://extensions.gnome.org/extension/4033/x11-gestures/
