### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [JoseExposito/gnome-shell-extension-x11gestures#49]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by JoseExposito** [comment]
Thanks for the heads up @yochananmarqos, I finished migrating the extension and I sent for review the [new release](https://github.com/JoseExposito/gnome-shell-extension-x11gestures/releases/tag/18) to extensions.gnome.org.

Other than minor changes to make the extension compatible with the latest GNOME, I have not made changes in months, so I won't send 2 releases, instead I'll focus on maintaining >= 45. I think that old versions of the extension will be available for installation.

**Comment by yochananmarqos** [comment]
@JoseExposito It's working fine with GNOME 45.rc, thanks!
