### ISSUE TITLE
Not working on Gnome 44

### ISSUE THREAD

**Issue by itsdotnet** [JoseExposito/gnome-shell-extension-x11gestures#50]
### Describe the bug

A clear and concise description of what the bug is and how to reproduce it.

### Expected behaviour

Tell us what should happen.

### Actual behaviour

Tell us what happens instead.

### Logs

If required, include logs of the bug:

```
$ journalctl -f -o cat /usr/bin/gnome-shell

```

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.

### Your environment

 * Extension version:
 * Touchégg version:
 * Operating System: Ubuntu, Fedora, Arch Linux...
 * GNOME Shell Version:
 * Are you using other GNOME Shell extensions?
    * List the other extensions
    * Can you reproduce the issue after disabling the other extensions?

**Comment by JoseExposito** [comment]
Please add the requested details, it's impossible to know what's going on without them.
