### ISSUE TITLE
Gesture to adjust volumn ( as on Window 11 )

### ISSUE THREAD

**Issue by totargaming** [JoseExposito/gnome-shell-extension-x11gestures#54]
### Is your feature request related to a problem? Please describe

Sound volume gesture:
> It is very frustrating when a sound is suddenly so noisy, as a touchpad enthusiast, I always hope I can do everything with my touchpad( in this case, drag up and down to adjust volume}. Therefore, this time I just realized that you might be able to make this possible

### Describe the solution you'd like

the operation should be simple, which is to use 3 or 4 fingers to turn up and down. 

### Describe alternatives you've considered

However, I see that at this stage, you still only have either 3 or 4 fingers. Therefore, this will be a breakthrough if you can extend the use of fingers touching flexibly.

Examples: if a user uses 3 fingers for window operation, 4 fingers dragging is for volume adjusting

**Comment by JoseExposito** [comment]
This is already possible, have a look to https://github.com/JoseExposito/touchegg/issues/576 and the linked issue.
