### ISSUE TITLE
  Gnome 45 Support?

### ISSUE THREAD

**Issue by akki01133** [JoseExposito/gnome-shell-extension-x11gestures#55]
I am wondering due to Gnome 45 switching to ESM will there be a new release supporting Gnome 45???

I get this error when opening the settings dialogue of the extension
` SyntaxError: import declarations may only appear at top level of a module `

Stack trace:
`
  @file:///home/ajeet/.local/share/gnome-shell/extensions/x11gestures@joseexposito.github.io/prefs.js:22:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  `

**Comment by JoseExposito** [comment]
Hi! 

Yes, there is a release under review that, hopefully, will be released in a few days. Closing this issue in favour of https://github.com/JoseExposito/gnome-shell-extension-x11gestures/issues/52
