### ISSUE TITLE
Extension Outdated

### ISSUE THREAD

**Issue by prathamvbhat** [JoseExposito/gnome-shell-extension-x11gestures#59]
Hello, The extension X11-gestures is really good and one of the extension that i use always use in my linux. After yersterday's gnome shell update to 46, this extension is declared as outdated and i anymore cannot use this in my Endavouros (Arch Linux).
It would be really helpfull if you could tell me what i can do to get the extension back.

**Comment by prathamvbhat** [comment]
![image](https://github.com/JoseExposito/gnome-shell-extension-x11gestures/assets/102966477/cae43523-290c-4669-a38e-74e920bdd5d2)

**Comment by JoseExposito** [comment]
Hi! 

I'm working on updating the extension. Depending on how GNOME Shell changed under the hood it might take me a few days.

I'll let you know the status of the process.

**Comment by JoseExposito** [comment]
It was easy :tada: I just sent the extension for review and should be available soon. Here is the new release:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/releases/tag/23

**Comment by prathamvbhat** [comment]
I really thank you for your prompt and speedy reply. I'll check and update it in my os.
The extension is working as good as it was previously. 
Thank you once again.
