### ISSUE TITLE
TypeError: obj._touchEggTracker is undefined

### ISSUE THREAD

**Issue by EliotKhachi** [JoseExposito/gnome-shell-extension-x11gestures#61]
I loved these gestures on my old laptop, but I have a new laptop now and I'm struggling with getting it to work. Not sure if I installed it properly.

1. Install touchegg
`sudo add-apt-repository ppa:touchegg/stable`
`sudo apt install touchegg`
`sudo apt install gnome-shell-extension-manager`

2. I cloned this repo and copied the contents to the gnome shell extensions manager folder
`cp -r . ~/.local/share/gnome-shell/extensions/x11gestures@joseexposito.github.io`

3. Installed gnome tweaks
`sudo apt install gnome-tweaks`

4. Logged out and in. The touchegg gestures are working, i.e. swipe up or down with 3 fingers to open activities or go back to workspaces, swipe left or right to switch workspaces-- but the additional swipe gestures from this repo that I really liked don't work. I used 4 finger swipes for workspace management and 3 finger swipes for window management. 
My touchegg is running...
```
● touchegg.service - Touchégg Daemon
     Loaded: loaded (/usr/lib/systemd/system/touchegg.service; enabled; preset:>
     Active: active (running) since Fri 2024-08-23 05:58:06 UTC; 16min ago
       Docs: https://github.com/JoseExposito/touchegg/tree/master/installation#>   Main PID: 8498 (touchegg)
      Tasks: 5 (limit: 18255)
     Memory: 3.1M (peak: 4.1M)
        CPU: 2.459s
     CGroup: /system.slice/touchegg.service
             └─8498 /usr/bin/touchegg --daemon

Aug 23 05:58:15 myoboku touchegg[8498]: libinput error: event4  - PIXA3854:00 0>
Aug 23 05:59:05 myoboku touchegg[8498]: New client connection request
Aug 23 05:59:05 myoboku touchegg[8498]: New client connected
Aug 23 06:02:55 myoboku touchegg[8498]: New client connection request
Aug 23 06:02:55 myoboku touchegg[8498]: New client connected
Aug 23 06:02:56 myoboku touchegg[8498]: Client disconnected
Aug 23 06:02:59 myoboku touchegg[8498]: Client disconnected
Aug 23 06:10:50 myoboku touchegg[8498]: New client connection request
Aug 23 06:10:50 myoboku touchegg[8498]: New client connected
Aug 23 06:11:00 myoboku touchegg[8498]: Client disconnected

```
And the extension shows up on the extension manager. At first no error showed, but I tried disabling and re-enabling it and got the error shown below:
![Screenshot from 2024-08-23 06-08-55](https://github.com/user-attachments/assets/92d1e5ca-0603-480e-858f-76720dec2938)

I have a feeling it may be my touchpad hardware. I am using an unconventional laptop (Framework 16), but I'd appreciate any guidance.
```
$ uname -a
Linux myoboku 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by JoseExposito** [comment]
> The touchegg gestures are working, i.e. swipe up or down with 3 fingers to open activities or go back to workspaces, swipe left or right to switch workspaces-- but the additional swipe gestures from this repo that I really liked don't work. I used 4 finger swipes for workspace management and 3 finger swipes for window management.

OK, if all gestures are working, that means that the problem is not with Touchégg, it must be somewhere else.

> And the extension shows up on the extension manager. At first no error showed, but I tried disabling and re-enabling it and got the error shown below

Could you click on "See Details" and copy and paste the output here, please?

This issue looks similar to https://github.com/JoseExposito/gnome-shell-extension-x11gestures/pull/60

But that was an user running this X11-only extension on Wayland. Just to double check, are you using the X11 session, right?

You can quickly check it in the terminal running:

```
$ echo $XDG_SESSION_TYPE
```

On the Wayland session gestures work out of the box, so there is no need to install this extension.

I'd try to disable every other extension, reboot and try again. Sometimes there might be conflicts between extensions.

**Comment by EliotKhachi** [comment]
I actually was on Wayland but I switch to Xorg and I'm facing the same issue. 4-finger swipes to switch between workspaces and the activities menu is working, but 3 finger swipes to maximize/minimize windows are not. I also tried disabling all other extensions and rebooting.

```
$ echo $XDG_SESSION_TYPE
x11
```
### Extensions Manager:
![Screenshot from 2024-08-23 17-51-01](https://github.com/user-attachments/assets/55ae3017-c6a3-4e63-b70d-e68f9c76c180)
### "See Details" Page:
![Screenshot from 2024-08-23 17-49-57](https://github.com/user-attachments/assets/51ead5c3-3223-42bb-ac7b-60a1e0bda4bb)

**Comment by dsheeler** [comment]
@EliotKhachi I can't help solve this but could you tell me how you configure things so that 3 fingers does the window min/max?

**Comment by EliotKhachi** [comment]
I actually don't remember. I thought this repo offered that functionality but I'm honestly not sure.

I recently found another extension that works out of the box on Wayland, Ubuntu 24.04.
Download the gnome shell extensions manager
`sudo apt install gnome-shell-extension-manager`
Go to "Browse" and look for amarullz window gesture. also found here [https://github.com/amarullz/windowgestures](https://github.com/amarullz/windowgestures)
Install and restart your system.

I really like these settings:

![Screenshot from 2024-08-24 05-39-30](https://github.com/user-attachments/assets/706a16cd-6f64-46c8-96fa-ab2d7a9779c2)
