### ISSUE TITLE
GNOME 47 support

### ISSUE THREAD

**Issue by bubner** [JoseExposito/gnome-shell-extension-x11gestures#62]
GNOME 47 was put into stable release yesterday

**Comment by matteodv99tn** [comment]
For the one interested in having the extension working in GNOME 47, you can try the following:

- go to your local shell extensions install directory (shall be ``.local/share/gnome-shell/extensions``, and navigate to this extensions (``x11gestures@joseexposito.github.io``);
- there update the ``metadata.json`` file by adding the 47th shell extension, as in my PR #63;
- reboot the PC.

After that, the extension shall work as before.

**Disclaimer:** I have never developed shell extensions, nor I worked with JS. I just tried to add the version number to this extension, and everything works (at least on my machine). Still, I don't know if this is the proper way to handle such dependency, or if something internally broke and I didn't noticed it yet.

**Comment by JoseExposito** [comment]
Thanks for the PR and for testing the extension. I just created a new release and pushed it to GNOME extensions. It'll available as soon as the review process finishes.
